server:
  port: 8080

spring:

  datasource:
    druid:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databaseName=KFSystem
      username: sa
      password: wscjw
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
    #配置文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.cheng.mapper

